services:
  db_pg:
    container_name: db_pg
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
      - php_vendor:/var/www/html/vendor
      - php_var:/var/www/html/var
    environment:
      DATABASE_URL: "postgresql://user:password@db_pg:5432/blog_db?serverVersion=15&charset=utf8"
      APP_ENV: dev
      JWT_SECRET_KEY: "/var/www/html/config/jwt/private.pem"
      JWT_PUBLIC_KEY: "/var/www/html/config/jwt/public.pem"
      JWT_PASSPHRASE: "8e20bedd67168a079fc0486de7278d119198a11ab847055a0ae020b5cec2a1ed"
    depends_on:
      - db_pg

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  vue:
    container_name: vue
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - vue_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - php

volumes:
  db_data:
  php_vendor:
  php_var:
  vue_modules:
